language: php
sudo: false
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.cache/bin"
  - "$HOME/.n98-magerun/modules"
  - "$HOME/.cache/magento"
php:
- 5.5
- 5.6
- 7.0
matrix:
  fast_finish: true
  allow_failures:
  - php: 5.6
    env: MAGENTO_VERSION=ce-1.8.1.0
  - php: 7.0
    env: MAGENTO_VERSION=ce-1.8.1.0
env:
  global:
  - APPNAME=Ffuenf_TransactionalEmails
  - secure: K1WPlxIpWTIMmUZrO8enLFrxbDUWyOUWe0Ezpp/FfC/xQHye2/lAbKlD/lgXTt8lhhhiq2pSfa06GOecmKHQ5eaTMcqcji0xAeLW8djbbdhP1aC7vcHvu+p6AbA2VB8sF3YZTLfKwnhJCFUsXW3tG4oV2AKy6IECHp2y0p9NJdy7J+f5k2OZKLASz5L98ZVuP18/N+43jGTvWAeWevjImRBi0Xlzf0Kdr0+dJ3BTpdZTgrLhoevcEbXv+S1BvUE2x+05BxwbYP77SLcmy/FMNr7GeX3F8VJDuaoIE1nmrWV3X2qTdkTfv8z7buXAhXOThFEbY2tsVm/u9oojN4FvGbDO2sozOHBRqchDTAtg0BdLod/j4DPhE4eN2OxDJMGMfhDalYEndf26DjkjQ9+B17cS7TEciwuhUrKMsFE6RUOFGHzpS6D5sleg1qkM0lZpMA28E+Ho6ipMFNu9tfzKPDqQ5l5J9yphfNcPhZMqi2LVOAwle2Ikv6orfcAxnBTGx1VLgMK/bHbl0NyKFxiiyEcYs0cT8HgyohDiwmElmi2vJ1Ru8417zsShmHsRNwcYw2N+xvw6Qo0Ypdrj4eIF79qGoIFtmYl7fkDIX/sqa0rn56UJc3ZKPMz/o4XTOxA0agSrzOC9J7FZ/8J4ct8jKjuDiGItTAUD0e3Wj0PBU3I=
  - secure: Wj1mTyw745DwIwltPFZN4KPHni2CuXuhrGTBLWQkK4Ly1BXqoW3lYybi7tdFPvVyCHNdjenaIfXXMaJYCTFe9/CLkqV2MJoa4pkWIMdP0LjWimSbwQJFkQBOlklsLYaPZ7YkJqexiQqEOAI52TW3nhQ1cVC+O9t7WBGjDuhNwp3m6Ui4Y8Z+84NWJBMMRsqVm/aZAVrO/pSuFpix2Teir0IiJJ/EqUAXmuhBPb6VPNQOiHBOnFIdFHlcdI9TPLywhhCwyxVBToLMMLnsiatKOP5FgZRuAqbMvuHAWu7dENsxJo3NxBtVUlKu/9ze5OabIjolVAzfkB2Xq8draumYfU6xhCzJO9vUU+QEx3H599pBtQ8C9IXYL30peKyfU+HVUUxjmZc/57EyFahI3AITr+rtbi13F+dTOUggSWGLx/L4fjdih8ld0oC2LVQQ85kh+QMoxHpfTAm85iJhFdv8HjQcjoe4Jv3aKk2jbk62Gf02k/2yrLQ9wtgwouMZscKLoN3sQc+pBEvMX7V8HNAG3b3e0kpD2GwmzmfAnumEi8dN0Zc3cIq0J0EBbyz22OeznJUycJhg1U/AbC1QsmwUT5+c3u6N8Ac947jFtRWyV1+KoNY0wyzJulih4m0UEHfY/8AWGyzTpKVFT34VUikjM76ZCMI9AdlFcaYSlNtP8do=
  - secure: kdl/o0zUPtYHwsWvzeWAXv/fEHzZP++3aSFFlMvCeiIsDA001Hgv3xTi9MaFPuxi4EOlnMxjvLbmO3GXzipmh6GHIwnLqo7PBjFxJrmXasI3fiI7xid1I9M8jNIxU4XvmlYA88/eUgiegR3LeRdC3SUhQhpN8+9nd6/DT0oRtT8NqmKo1+j14Y7YX3Qtwv2wbaCW+tPU1OcOC1KlObjqgURgWJf7ehFQ32sNwvKDW31ha4pbq4gGI272pxu4vGsHO2py5GlvGyQsfjoFfE9U35w22eqwbj/4rbNu22S5NwBOaJAWd/5SDmfx9j468UZucE9XJApguKyue8yxqzSJra2x7lmBZnJWbmbKTHklM+Kf2mDwpPRcV+CYe2lHxvO00bQ5Xlf0JcU+/4gnGhizs1gr7FpSceWcxFSz16R4zxNusNCUBr8B6HT3cCw+UijPOFoDXJOwJ+c6FhxLAXbt2xvkEjpi7RtA0DlbyKdLhxlF2Du93MufcS6JykuSjuVG1N2Nc28R1ocPkXI6Ycx0leU3lW6EFtQF4RYXBd9Vx5ng+Z6X+0oOdpvDwFrsSfNShG1I5b4bun3iYqwFvv25+ulGp+u848SMoz+v8Sr9VM1pLnyIlnj51+yv3OvJnSpvzRabjeL2Qe7IldHgdrHFYFXiXN95K8EWEGj5rb7AWJk=
  matrix:
  - MAGENTO_VERSION=ce-1.9.2.4
  - MAGENTO_VERSION=ce-1.9.1.1
  - MAGENTO_VERSION=ce-1.8.1.0
  - MAGENTO_VERSION=ce-1.7.0.2
  - MAGENTO_VERSION=ce-1.6.2.0
before_install:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/before_install.sh
  | bash
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/script.sh
  | bash
deploy:
  provider: releases
  file:
  - "${APPNAME}-${TRAVIS_TAG}.zip"
  - "${APPNAME}-${TRAVIS_TAG}.tar.gz"
  skip_cleanup: true
  on:
    branch: master
    tags: true
  api_key:
    secure: ebRkIpmsMl/7YlyCsEVlH86/Gu+7O9CqJp+8h6HT0iKmd7o3RGACRWQuLDjY4+QvBpfqLlDbdJOe1Z+PCff1vpHV/d8gIfdgSvbTjnzxDRLzRdO6Ns3XdevOvkHy85ubCYKrVaLu3Vz30MxHhNALJG14GMxHT1vVqhEGDEQoCv+MhIR3AszStSj1con3JcRNEiwgCwTR13a4hUe+FvBYgcvDMXOohCNAJJs1bxTePjXiF15jMhZ2SxePDZwItB377WoIK/rk/AU/Pgfl2Ai9EGVIpiONmdVEUq8iXB0ehRF4lwpmGnAIv9Gt+Chw8H9uxo6Bh1h/pHBizFQRBQN1AGDUndV+8GH8gqeFL5tZ/1XfuaFR1Ln13xlNg0ZMQf8xUKXsXt1QEKKDSClIQh4grYTF9LPksyeExCzmCjgmYbBht/cUAMtX9ueQlYo4vCKgxIclo+njPL7/ScClVqjKsxTOz2MUEtsj9gY1wDrxiWwiUV1r27he0xnbY4VJe6sRXcTHcv9+nr4/eLSsDDvcvXnVOxAnJhugnakRnC/qPkZQs2LtJ5cY3b/Gu4FL7pjnCwIIGYR2ZpHXKvwV4X73/ICvS5yy9diNZf5MPdNi25gbGF5/AeBlqvoV2HM4i9wKYs953+/hCBHfE+xXmEOII6gaEAFHz8UMgFNaInRTUCw=
notifications:
  slack:
    secure: DoohRt9O1zrzsKHYGj6xbaoS18iReEIbkrwmUduOoFqgoXqcjtXezQs/0bS4nnal9qGVDCISC1pxNYqZVt0QOioxs8Kd5TYz0J6pnvQVzgqcVTRECrXN07tufzzKhDGLSv6FpizbnFML7gKomjGgufLRQxuVIqSljpvt6P3P3KtnSPX2SeV+/mTQV6TiUYCMSOH3mg5RtTiVCvn/fQNKB2OmoTfsOzHDnzcHK32sq6dW9JHcQXWzbb1JnFD+sq80AOHvo9mdI2Eq3kyQYVIYqPVw3uwgRdikcNlKnypgib0cUDqi9F1ciKCL3yPyVoFg5xSs7hmnbUTqCZWGaTX9ZP3xeYHTBrLJoqYn9r+HvHRxb72B7JKXTk+qJOItXbR040nLQn7fEoJzMbw4wS5YR2RgvNC6Bm2CADIKc2PptmbHQp7eSzuaH0mC+RM7TiaW7FrQbUdaNHQeOzKdk00ZI0/ZwlZn3DuQkjAe/wnxu89t/iOChSE40PPyMhz9RQVrfH7LrnkHSERN4+Vxn5yGDL4MGmw981VXgeyus35fD2aGPfYwBEBoazAN/bHp+rR1MkSPHS9h7wAXuUFQU784PB/JAZ6qoZ7pbYlniUcCR74qvwrrYYpkQv69PyY1Vg13XRoXuEsR2W+iGzb7wTquR8xXo1XtS1ThGe4iTyvDnX4=
